services:
  db:
    image: postgres:latest
    container_name: db-montesuadieta
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      driver: json-file
      options:
        max-size: 100m
  backend:
      image: fabioviniciusfsiqueira/montesuadieta-backend:latest
      container_name: api-montesuadieta
      restart: always
      environment:
        DATABASE_URL: "postgresql://postgres:senha123@db:5432/devdb?schema=public"
        SECRET: suaChaveSecretaSuperSegura123!@#
        PORT: 3000
      ports:
        - "3000:3000"
      depends_on:
        - db
      command: >
        sh -c "npm run migrate:dev && npm run dev"
volumes:
  pgdata:
