services:
  db:
    image: postgres:latest
    container_name: dbmontesuadieta
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      driver: json-file
      options:
        max-size: 100m
volumes:
  pgdata:
